In [2]:
import pandas as pd
from dotenv import load_dotenv
import os
from urllib.parse import quote_plus
from sqlalchemy import create_engine

In [3]:
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")

In [4]:
password = quote_plus(DB_PASSWORD)

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{password}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

engine = create_engine(DATABASE_URL)

print("Connected Successfully!")

Connected Successfully!

In [5]:
query = """
SELECT *
FROM telco_customer_churn
LIMIT 5;
"""

pd.read_sql(query, engine)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
query = """
SELECT COUNT(*) AS total_customers
FROM telco_customer_churn;
"""

pd.read_sql(query, engine)

   total_customers
0             7032

In [9]:
query = """
SELECT
    "Churn",
    COUNT(*) AS customer_count
FROM telco_customer_churn
GROUP BY "Churn";
"""

pd.read_sql(query, engine)

  Churn  customer_count
0    No            5163
1   Yes            1869

In [17]:
query = """
SELECT
ROUND(AVG("MonthlyCharges")::numeric, 2)
AS avg_monthly_charge
FROM telco_customer_churn;
"""

pd.read_sql(query, engine)

   avg_monthly_charge
0                64.8

In [18]:
query = """
SELECT
    "Contract",
    COUNT(*) AS customers
FROM telco_customer_churn
GROUP BY "Contract"
ORDER BY customers DESC;
"""

pd.read_sql(query, engine)

         Contract  customers
0  Month-to-month       3875
1        Two year       1685
2        One year       1472